apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zakamaldin-helm1.name" . }}
  labels:
    {{- include "zakamaldin-helm1.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "zakamaldin-helm1.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zakamaldin-helm1.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.proxy }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        volumeMounts:
        - name: configs
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: configs
        configMap:
          name: {{ include "zakamaldin-helm1.name" . }}


