apiVersion: v1
kind: Service
metadata:
  name: {{ include "zakamaldin-helm1.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "zakamaldin-helm1.selectorLabels" . | nindent 4 }}
  ports:
      {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- end }}