---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
- name: Install Vector
  hosts: vector
  roles:
    - vector-role
- name: Install LigthHouse
  hosts: lighthouse
  roles:
    - lighthouse-role
