apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"nginx"},"name":"deployment-1","namespace":"lesson3"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.14.2","name":"nginx"},{"env":[{"name":"HTTP_PORT","value":"8080"}],"image":"wbitt/network-multitool:latest","name":"multitool","ports":[{"containerPort":8080}]}]}}}}
  creationTimestamp: "2024-05-28T22:52:54Z"
  generation: 8
  labels:
    app: nginx
  name: deployment-1
  namespace: lesson3
  resourceVersion: "231637"
  uid: 13497065-e1cf-4f1f-ace8-c8dc9841e12a
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - env:
        - name: HTTP_PORT
          value: "8080"
        image: wbitt/network-multitool:latest
        imagePullPolicy: Always
        name: multitool
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2024-05-28T22:52:55Z"
    lastUpdateTime: "2024-05-29T15:37:47Z"
    message: ReplicaSet "deployment-1-5b949c5858" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-05-31T17:33:23Z"
    lastUpdateTime: "2024-05-31T17:33:23Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 8
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 2
