apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: hw10-1
    meta.helm.sh/release-namespace: hw10
  creationTimestamp: "2024-06-23T14:48:31Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: zakamaldin-helm1
  namespace: hw10
  resourceVersion: "1023140"
  uid: ded7c79f-0846-4b88-b868-0ba4b7f1c77d
spec:
  clusterIP: 10.152.183.91
  clusterIPs:
  - 10.152.183.91
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/instance: hw10-1
    app.kubernetes.io/name: zakamaldin-helm1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
