apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: hw14
  labels:
    app: web
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: dockerhub.timeweb.cloud/nginx:1.20
      - name: multitool
        image:  dockerhub.timeweb.cloud/wbitt/network-multitool:latest
        env:
        - name: HTTP_PORT
          value: "8080"
        ports:
        - containerPort: 8080
