{
 "title": "CPU",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU current",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100) "
    }
   ]
  },
  {
   "title": "CPU usage by core",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "CPU usage avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "1m"
    },
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "5m"
    },
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[15m])) * 100)",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "RAM Available" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "RAM Free" }
   ]
  },
  {
   "title": "Free Disk(Gb)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} - node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Free disk(%)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  }
 ]
}