kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-2
  labels:
    vol: pvc-2
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi