apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw7-2
  labels:
    app: hw7-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw7-2
  template:
    metadata:
      labels:
        app: hw7-2
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool:latest
        env:
        - name: HTTP_PORT
          value: "8080"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: myvol
          mountPath: /from_nfs
      volumes:
      - name: myvol
        persistentVolumeClaim:
          claimName: pvc-2