node("linux"){

    parameters{
        bool(name: 'PROD_RUN', defaultValue: 'False')
    }
    stage("Git checkout"){
        git url: 'https://github.com/aragastmatb/example-playbook'
    }
    stage("Sample define secret_check"){
        secret_check=params.PROD_RUN
    }
    stage("Run playbook"){
        if (secret_check){
            sh 'ansible-playbook site.yml -i inventory/prod.yml'
        }
        else{
            sh 'ansible-playbook site.yml -i inventory/prod.yml --check --diff'
        }  
    }
}