apiVersion: v1
kind: Service
metadata:
  name: deployment-1-svc
spec:
  selector:
    app: nginx
  ports:
    - name: web
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: network
      protocol: TCP
      port: 9002
      targetPort: 8080