apiVersion: v1
kind: Service
metadata: 
  name: deployment-1-nodeport-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports: 
  - name: web
    port: 9003
    targetPort: 80
    nodePort: 30001
    protocol: TCP
  - name: network
    port: 9004
    targetPort: 8080
    nodePort: 30002
    protocol: TCP