---
all:
  hosts:
    nexus-01:
      ansible_host: 178.154.205.13  
    sonar-01:
      ansible_host: 178.154.204.250  
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: centos

    1f2c66091d141fcf6e3fe85ef3d2b7837ebea5ca