---
all:
  hosts:
    jenkins-agent-01:
      ansible_host: 51.250.70.86  
    jenkins-master-01:
      ansible_host: 51.250.64.36  
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: fedora